loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views


app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

produto/urls.py
from django.urls import path
from . import views


app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(),
         name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
    path('busca/', views.Busca.as_view(), name='busca'),
]

pedido/models.py
from django.db import models
from django.contrib.auth.models import User


class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default='C',
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self):
        return f'Pedido N. {self.pk}'


class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

pedido/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from produto.models import Variacao
from utils import utils
from .models import Pedido, ItemPedido


class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(usuario=self.request.user)
        return qs


class Pagar(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pedido/pagar.html'
    model = Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'


class SalvarPedido(View):
    template_name = 'pedido/pagar.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login.'
            )
            return redirect('perfil:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Carrinho vazio.'
            )
            return redirect('produto:lista')

        carrinho = self.request.session.get('carrinho')
        carrinho_variacao_ids = [v for v in carrinho]
        bd_variacoes = list(
            Variacao.objects.select_related('produto')
            .filter(id__in=carrinho_variacao_ids)
        )

        for variacao in bd_variacoes:
            vid = str(variacao.id)

        error_msg_estoque = ''

        estoque = variacao.estoque
        qtd_carrinho = carrinho[vid]['quantidade']
        preco_unt = carrinho[vid]['preco_unitario']
        preco_unt_promo = carrinho[vid]['preco_unitario_promocional']

        if estoque < qtd_carrinho:
            carrinho[vid]['quantidade'] = estoque
            carrinho[vid]['preco_quantitativo'] = estoque * preco_unt
            carrinho[vid]['preco_quantitativo_promocional'] = estoque * \
                preco_unt_promo

            error_msg_estoque = 'Estoque insuficiciente para algun(s) produtos d seu carrinho. '\
                'Reduzimos a quantidade desses produtos. Por favor, verifique '\
                'quais produtos foram afetados a seguir.'

            if error_msg_estoque:
                messages.error(
                    self.request,
                    error_msg_estoque
                )
                self.request.session.save()
                return redirect('produto:carrinho')

        qtd_total_carrinho = utils.cart_total_qtd(carrinho)
        valor_total_carrinho = utils.cart_totals(carrinho)

        pedido = Pedido(
            usuario=self.request.user,
            total=valor_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status='C',
        )
        pedido.save()

        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promocional=v['preco_quantitativo_promocional'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )

        contexto = {
            'qtd_total_carrinho': qtd_total_carrinho,
            'valor_total_carrinho': valor_total_carrinho,
        }

        del self.request.session['carrinho']
        return redirect(
            reverse(
                'pedido:pagar',
                kwargs={
                    'pk': pedido.pk
                }
            )
        )


class Detalhe(DispatchLoginRequiredMixin, DetailView):
    model = Pedido
    context_object_name = 'pedido'
    template_name = 'pedido/detalhe.html'
    pk_url_kwarg = 'pk'


class Lista(DispatchLoginRequiredMixin, ListView):
    model = Pedido
    context_object_name = 'pedidos'
    template_name = 'pedido/lista.html'
    paginate_by = 10
    ordering = ['-id']

templates/parciais/_carrinho.html
{% load static %}
{% load produtofilters %}


<div class="table-responsive">
    <table class="table">

        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>Var.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>

        {% for linha in carrinho.values %}
        <tr>
            <td class="d-none d-lg-block">
                <img class="cart-img" src="{% get_media_prefix %}{{ linha.imagem }}">
            </td>
            <td>
                <a href="{% url 'produto:detalhe' linha.slug %}">
                    {{ linha.produto_nome }}
                </a>
                <a class="ml-3" href="{% url 'produto:removerdocarrinho' %}?vid={{ linha.variacao_id }}">
                    <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                </a>
            </td>
            <td>{{ linha.variacao_nome }}</td>
            <td>
                {{ linha.quantidade }} x
                {% if linha.preco_unitario_promocional|formata_preco %}
                {{ linha.preco_unitario_promocional|formata_preco}}
                {% else %}
                {% if linha.preco_unitario|formata_preco %}
                {% endif %}
                {% endif %}
            </td>

            {% if linha.preco_quantitativo_promocional %}
            <td>{{ linha.preco_quantitativo_promocional|formata_preco }}</td>
            {% else %}
            <td>{{ linha.preco_quantitativo|formata_preco }}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
</div>

templates/parciais/_footer.html
{% load static %}

<footer class="container-fluid bg-primary pt-3 pb-2">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Feito com Django</span>
                </div>
            </div>
            <div class="col">
                <div class="mt-1 text-right">
                    <span class="align-middle p-1">Por Herbety Paulo</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js' %}"></script>
<script src="{% static 'assets/custom/js/scripts.js' %}"></script>

templates/parciais/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css' %}">
<link rel="icon" sizes="192x192" href="https://static.djangoproject.com/img/icon-touch.e4872c4da341.png">

templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/parciais/_nav.html
{% load produtofilters %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'produto:lista' %}">E-commerce Fictício</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'produto:lista' %}">Home <span class="sr-only">(current)</span></a>
            </li>

            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Conta
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'pedido:lista' %}">Meus pedidos</a>
                    <a class="dropdown-item" href="{% url 'perfil:criar' %}">Atualizar dados</a>
                    <a class="dropdown-item" href="{% url 'perfil:logout' %}">Sair</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'perfil:criar' %}">Entrar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'perfil:criar' %}">Criar conta</a>
            </li>
            {% endif %}

            {% if request.session.carrinho %}
            <li class="nav-item">
                <a class="nav-link nav-cart-link active" href="{% url 'produto:carrinho' %}">
                    <span class="nav-cart-text mr-1">
                        Carrinho
                    </span>
                    <span class="nav-cart-count mr-1">
                        <strong>{{ request.session.carrinho|cart_total_qtd}}x</strong>
                    </span>
                    <span class="nav-cart-icon mr-2">
                        <i class="fas fa-shopping-cart"></i>
                    </span>
                </a>
            </li>
            {% endif %}


        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'produto:busca'  %}">
            <input name="termo" value="{{ request.GET.termo }}" class="form-control mr-sm-2" type="search"
                placeholder="Busca" aria-label="Busca">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Busca</button>
        </form>
    </div>
</nav>

templates/parciais/_pagination.html
{% if is_paginated %}

<div class="col mt-3 mb-3">
    <div class="row">
    </div>

    <div class="pagination">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">&laquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
            </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}

            {% if page_obj.number == num %}
            <li class="page-item active">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endif %}

            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>
{% endif %}

templates/parciais/_pedido.html
{% load static %}

{% load produtofilters %}


<div class="row">
    <div class="col">
        <h3>{{ pedido }}</h3>
        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
            <div class="col-lg-4">{{ pedido.id }}</div>
            <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
            <div class="col-lg-4">{{ pedido.total|formata_preco }}</div>

            <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
            <div class="col-lg-4">{{ pedido.qtd_total }}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{ pedido.get_status_display }}</div>
        </div>
        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>
        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>

                {% for linha in pedido.itempedido_set.all %}
                <tr>
                    <td class="d-none d-lg-block">
                        <img class="cart-img" src="{% get_media_prefix %}{{ linha.imagem }}">
                    </td>
                    <td>{{ linha.produto }}</td>
                    <td>{{ linha.variacao }}</td>
                    <td>{{ linha.quantidade }}</td>
                    <td>{% if linha.preco_promocional %}
                        {{ linha.preco_promocional|formata_preco }}
                        {% else %}
                        {{ linha.preco|formata_preco }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>