loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views


app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
]

pedido/models.py
from django.db import models
from django.contrib.auth.models import User


class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default='C',
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self):
        return f'Pedido N. {self.pk}'


class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

pedido/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from produto.models import Variacao
from utils import utils
from .models import Pedido, ItemPedido


class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(usuario=self.request.user)
        return qs


class Pagar(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pedido/pagar.html'
    model = Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'


class SalvarPedido(View):
    template_name = 'pedido/pagar.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login.'
            )
            return redirect('perfil:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Carrinho vazio.'
            )
            return redirect('produto:lista')

        carrinho = self.request.session.get('carrinho')
        carrinho_variacao_ids = [v for v in carrinho]
        bd_variacoes = list(
            Variacao.objects.select_related('produto')
            .filter(id__in=carrinho_variacao_ids)
        )

        for variacao in bd_variacoes:
            vid = str(variacao.id)

        error_msg_estoque = ''

        estoque = variacao.estoque
        qtd_carrinho = carrinho[vid]['quantidade']
        preco_unt = carrinho[vid]['preco_unitario']
        preco_unt_promo = carrinho[vid]['preco_unitario_promocional']

        if estoque < qtd_carrinho:
            carrinho[vid]['quantidade'] = estoque
            carrinho[vid]['preco_quantitativo'] = estoque * preco_unt
            carrinho[vid]['preco_quantitativo_promocional'] = estoque * \
                preco_unt_promo

            error_msg_estoque = 'Estoque insuficiciente para algun(s) produtos d seu carrinho. '\
                'Reduzimos a quantidade desses produtos. Por favor, verifique '\
                'quais produtos foram afetados a seguir.'

            if error_msg_estoque:
                messages.error(
                    self.request,
                    error_msg_estoque
                )
                self.request.session.save()
                return redirect('produto:carrinho')

        qtd_total_carrinho = utils.cart_total_qtd(carrinho)
        valor_total_carrinho = utils.cart_totals(carrinho)

        pedido = Pedido(
            usuario=self.request.user,
            total=valor_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status='C',
        )
        pedido.save()

        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promocional=v['preco_quantitativo_promocional'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )

        contexto = {
            'qtd_total_carrinho': qtd_total_carrinho,
            'valor_total_carrinho': valor_total_carrinho,
        }

        del self.request.session['carrinho']
        return redirect(
            reverse(
                'pedido:pagar',
                kwargs={
                    'pk': pedido.pk
                }
            )
        )


class Detalhe(DispatchLoginRequiredMixin, DetailView):
    model = Pedido
    context_object_name = 'pedido'
    template_name = 'pedido/detalhe.html'
    pk_url_kwarg = 'pk'


class Lista(DispatchLoginRequiredMixin, ListView):
    model = Pedido
    context_object_name = 'pedidos'
    template_name = 'pedido/lista.html'
    paginate_by = 10
    ordering = ['-id']

pedido/templates/pedido/detalhe.html
{% extends 'base.html' %}

{% load produtofilters %}

{% load static %}

{% block titulo %}{{ pedido }} | {% endblock %}

{% block conteudo %}

{% include 'parciais/_pedido.html' %}

{% endblock %}

pedido/templates/pedido/lista.html
{% extends 'base.html' %}

{% load produtofilters %}

{% block titulo %}Pedidos de {{ user }} | {% endblock %}

{% block conteudo %}

<div class="row">
    <div class="col">
        <h3 class="mb-4">Pedidos de {{ user }}</h3>
        <p>Abaixo todos os seus pedidos realizados na loja.</p>
        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th scope="col">Pedido</th>
                    <th scope="col">Total</th>
                    <th scope="col">Qtd. Itens</th>
                    <th scope="col">Status</th>
                    <th scope="col">Mais detalhes</th>
                </tr>

                {% for pedido in pedidos %}
                <tr>
                    <th scope="row">{{ pedido }}</td>
                    <td>{{ pedido.total|formata_preco }}</td>
                    <td>{{ pedido.qtd_total }}</td>
                    <td>{{ pedido.get_status_display }}</td>
                    <td>
                        <a href="{% url 'pedido:detalhe' pedido.id %}">
                            Ver <i class="fas fa-search-plus ml-2"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% include 'parciais/_pagination.html' %}

{% endblock %}

pedido/templates/pedido/pagar.html
{% extends 'base.html' %}

{% load produtofilters %}

{% load static %}

{% block titulo %}Pagamento | {% endblock %}

{% block conteudo %}


<div class="row">
    <div class="col">
        <h3>Escolha o método de pagamento</h3>
        <p>Para o desenvolvedor: adicione seu método de pagamento preferido.</p>
    </div>
</div>

{% include 'parciais/_pedido.html' %}

<div class="row mt-4">
    <div class="col">
        <a href="#" class="btn btn-primary btn-block btn-lg">Pagar</a>
    </div>
</div>


{% endblock %}